// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcGheS35QN_nd-xkqAPTMPm8oII3baA3s',
    appId: '1:708617171275:web:34b64323f6c9b0f81db8ce',
    messagingSenderId: '708617171275',
    projectId: 'resumebuilder-pk',
    authDomain: 'resumebuilder-pk.firebaseapp.com',
    databaseURL: 'https://resumebuilder-pk-default-rtdb.firebaseio.com',
    storageBucket: 'resumebuilder-pk.firebasestorage.app',
    measurementId: 'G-K7HJJD3BJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1de_TuuhmK3f4B57JDREQMWhusXhd5UA',
    appId: '1:708617171275:android:fe28741927f013d41db8ce',
    messagingSenderId: '708617171275',
    projectId: 'resumebuilder-pk',
    databaseURL: 'https://resumebuilder-pk-default-rtdb.firebaseio.com',
    storageBucket: 'resumebuilder-pk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6inIvfOtJ8VNYHCb06Dh4HkD8pFWMYy4',
    appId: '1:708617171275:ios:da487cd855470afc1db8ce',
    messagingSenderId: '708617171275',
    projectId: 'resumebuilder-pk',
    databaseURL: 'https://resumebuilder-pk-default-rtdb.firebaseio.com',
    storageBucket: 'resumebuilder-pk.firebasestorage.app',
    iosClientId: '708617171275-l9loepl3kqlqrgost04uin00td8bnt5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumebuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6inIvfOtJ8VNYHCb06Dh4HkD8pFWMYy4',
    appId: '1:708617171275:ios:da487cd855470afc1db8ce',
    messagingSenderId: '708617171275',
    projectId: 'resumebuilder-pk',
    databaseURL: 'https://resumebuilder-pk-default-rtdb.firebaseio.com',
    storageBucket: 'resumebuilder-pk.firebasestorage.app',
    iosClientId: '708617171275-l9loepl3kqlqrgost04uin00td8bnt5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumebuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcGheS35QN_nd-xkqAPTMPm8oII3baA3s',
    appId: '1:708617171275:web:1095fd498c4bf0d31db8ce',
    messagingSenderId: '708617171275',
    projectId: 'resumebuilder-pk',
    authDomain: 'resumebuilder-pk.firebaseapp.com',
    databaseURL: 'https://resumebuilder-pk-default-rtdb.firebaseio.com',
    storageBucket: 'resumebuilder-pk.firebasestorage.app',
    measurementId: 'G-GHS45QSQ8X',
  );
}
